### ISSUE TITLE
Regarding Porting

### ISSUE THREAD

**Issue by RandomAltThing** [Synapz1/AdminEssentials#2]
@Synapz1

May I port this plugin to PocketMine-MP? (The Minecraft: Pocket Edition Server Software). All credits will be given and with your permission I would even add **more** commands than are already in this one.
All I need is for you to reply giving your permission (if you will) and I will be able to port then publish on forums.pocketmine.net

Thanks for the great plugin and I hope you take my request into consideration!

**Comment by Synapz1** [comment]
Sure you can port this plugin to PocketMine-MP. Thank you for asking first to make sure you have to permission and giving me credit. When its done can you link me to it? I would love to check it out. Send it in pm here and I can link it on my Bukkit page if you would like. My Bukkit dev is Synapzz in case you needed to know.

**Comment by RandomAltThing** [comment]
I have ported most of it, but what is the <code>announce</code> command? Is there a screenshot that shows what it looks like so I interperate it

**Comment by Synapz1** [comment]
![jdsjfgv](https://cloud.githubusercontent.com/assets/6752306/9007352/69531ac0-375e-11e5-9203-d1b443b05aa8.jpg)

It just basically sends a message to everyone on the server
