### ISSUE TITLE
Add /info

### ISSUE THREAD

**Issue by TheDiamondYT1** [Synapz1/AdminEssentials#3]
I would add this myself but I'm not the most experienced at bukkit. However I can do java and this is an admin plugins so why not this. You could do

``` java
(Command stuff)
public void onCommand(stuff){
sender.sendMessage("Your UUID: "sender.getUniqueId());
}

public void onConsoleCommand(stuff){
Player p = Bukkit.getServer().getPlayer(args[1]);
sender.sendMessage(p + "'s UUID: " + p.getUniqueId());
}
```

I have checked and this is in the API

**Comment by Synapz1** [comment]
Wow, sorry I did not see this message until 8 days later. I didn't get a notification for some reason...

So what do you mean by adding this? Where? Why do I need their UUID?

**Comment by RandomAltThingy** [comment]
It could be useful and I've seen it in another plugin (Can't remember now)

**Comment by Synapz1** [comment]
Oh, you mean like sending the player's UUID on all commands?

**Comment by RandomAltThingy** [comment]
It displays yours or someone else's UUID, possible for debug reasons.

**Comment by Synapz1** [comment]
Yeah, well in Bukkit when people join it says their UUID in console. Plus I'm sure online there is a tool that would get the UUID of a player if a server owner really needed it. And UUID's are usually just for internal use in the plugin so no need to display it out.

**Comment by RandomAltThingy** [comment]
How about adding support for offline players.

**Comment by RandomAltThingy** [comment]
Well make some sort of command to get private player info like IP etc available to admins only. This could be abused for ddosing and stuff so set it to false.

**Comment by RandomAltThingy** [comment]
The permission to false

**Comment by Synapz1** [comment]
I've been defintaly thinking about adding the ip check feature. But the plugin already does support offline players (as long as that played joined the server before)

**Comment by RandomAltThingy** [comment]
Maybe a command you do /(cmdname) <player> and it prints out
```
User: ExamplePerson101
FirstPlayed: 10 may 2007
LastPlayed: Today 9 am
IP: 192.168.0.9
```
Or something like that

**Comment by Synapz1** [comment]
I can do that.

**Comment by TheDiamondYT1** [comment]
@Synapz1 I am going to do another port, but alot better this time and will be on https://GitHub.com/EvolSoft.

Should I make it **AdminEssentials** or **AdminEssentialsPE**?

**Comment by Synapz1** [comment]
PE would be better so there is less confusion

**Comment by TheDiamondYT1** [comment]
Alright
